# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://techolas23.github.io/deck_of_cards/"

git_url = "https://github.com/techolas23/deck_of_cards/tree/master/"

def custom_doc_links(name): return None
